version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: direct
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
